[2025-03-26T12:20:37.040+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T12:20:37.165+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: historical_weather_etl.run_historical_script manual__2025-03-26T12:20:34.870301+00:00 [queued]>
[2025-03-26T12:20:37.177+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: historical_weather_etl.run_historical_script manual__2025-03-26T12:20:34.870301+00:00 [queued]>
[2025-03-26T12:20:37.180+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-26T12:20:37.196+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_historical_script> on 2025-03-26 12:20:34.870301+00:00
[2025-03-26T12:20:37.204+0000] {standard_task_runner.py:72} INFO - Started process 82427 to run task
[2025-03-26T12:20:37.208+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'historical_weather_etl', 'run_historical_script', 'manual__2025-03-26T12:20:34.870301+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/historical_dag.py', '--cfg-path', '/tmp/tmpteqs_nl1']
[2025-03-26T12:20:37.211+0000] {standard_task_runner.py:105} INFO - Job 85: Subtask run_historical_script
[2025-03-26T12:20:37.294+0000] {task_command.py:467} INFO - Running <TaskInstance: historical_weather_etl.run_historical_script manual__2025-03-26T12:20:34.870301+00:00 [running]> on host 3c3c1f66214b
[2025-03-26T12:20:37.398+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='historical_weather_etl' AIRFLOW_CTX_TASK_ID='run_historical_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T12:20:34.870301+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T12:20:34.870301+00:00'
[2025-03-26T12:20:37.403+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-26T12:20:37.406+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-26T12:20:37.408+0000] {logging_mixin.py:190} INFO - Current task name:run_historical_script state:running start_date:2025-03-26 12:20:37.166848+00:00
[2025-03-26T12:20:37.410+0000] {logging_mixin.py:190} INFO - Dag name:historical_weather_etl and current dag run status:running
[2025-03-26T12:20:37.413+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T12:20:37.417+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-26T12:20:37.423+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/historical.py']
[2025-03-26T12:20:37.436+0000] {subprocess.py:99} INFO - Output:
[2025-03-26T12:20:39.890+0000] {subprocess.py:106} INFO - 25/03/26 12:20:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-26T12:20:40.047+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-26T12:20:40.048+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-26T12:20:53.218+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 8) / 8]                                                                                25/03/26 12:20:53 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 24)
[2025-03-26T12:20:53.221+0000] {subprocess.py:106} INFO - java.sql.BatchUpdateException: Batch entry 1 INSERT INTO daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2021-01-01 09:00',7.1,16.1,67,7.1,0.0,'Sunny','//cdn.weatherapi.com/weather/64x64/day/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.222+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-26T12:20:53.223+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-26T12:20:53.224+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-26T12:20:53.225+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1416)
[2025-03-26T12:20:53.226+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1441)
[2025-03-26T12:20:53.227+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:506)
[2025-03-26T12:20:53.228+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-26T12:20:53.230+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-26T12:20:53.231+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-26T12:20:53.232+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:748)
[2025-03-26T12:20:53.233+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-26T12:20:53.234+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-26T12:20:53.235+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-26T12:20:53.237+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-26T12:20:53.239+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-26T12:20:53.240+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-26T12:20:53.241+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-26T12:20:53.242+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-26T12:20:53.243+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-26T12:20:53.245+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-26T12:20:53.246+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-26T12:20:53.248+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-26T12:20:53.249+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-26T12:20:53.250+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-26T12:20:53.251+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-26T12:20:53.252+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-26T12:20:53.253+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.255+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.
[2025-03-26T12:20:53.256+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-26T12:20:53.257+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-26T12:20:53.258+0000] {subprocess.py:106} INFO - 	... 23 more
[2025-03-26T12:20:53.259+0000] {subprocess.py:106} INFO - 25/03/26 12:20:53 WARN TaskSetManager: Lost task 0.0 in stage 4.0 (TID 24) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 1 INSERT INTO daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2021-01-01 09:00',7.1,16.1,67,7.1,0.0,'Sunny','//cdn.weatherapi.com/weather/64x64/day/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.260+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-26T12:20:53.261+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-26T12:20:53.262+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-26T12:20:53.263+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1416)
[2025-03-26T12:20:53.264+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1441)
[2025-03-26T12:20:53.265+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:506)
[2025-03-26T12:20:53.265+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-26T12:20:53.266+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-26T12:20:53.267+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-26T12:20:53.269+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:748)
[2025-03-26T12:20:53.270+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-26T12:20:53.272+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-26T12:20:53.273+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-26T12:20:53.274+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-26T12:20:53.275+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-26T12:20:53.276+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-26T12:20:53.277+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-26T12:20:53.278+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-26T12:20:53.279+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-26T12:20:53.280+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-26T12:20:53.281+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-26T12:20:53.283+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-26T12:20:53.284+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-26T12:20:53.285+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-26T12:20:53.286+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-26T12:20:53.288+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-26T12:20:53.289+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.290+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.
[2025-03-26T12:20:53.291+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-26T12:20:53.292+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-26T12:20:53.293+0000] {subprocess.py:106} INFO - 	... 23 more
[2025-03-26T12:20:53.294+0000] {subprocess.py:106} INFO - 
[2025-03-26T12:20:53.295+0000] {subprocess.py:106} INFO - 25/03/26 12:20:53 ERROR TaskSetManager: Task 0 in stage 4.0 failed 1 times; aborting job
[2025-03-26T12:20:53.534+0000] {subprocess.py:106} INFO - +-----+----------------+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-03-26T12:20:53.535+0000] {subprocess.py:106} INFO - |city |local_time      |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-03-26T12:20:53.537+0000] {subprocess.py:106} INFO - +-----+----------------+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-03-26T12:20:53.538+0000] {subprocess.py:106} INFO - |elche|2021-01-01 04:00|6.0        |6.0     |73      |6.0      |0.0      |Mostly Clear |//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-26T12:20:53.540+0000] {subprocess.py:106} INFO - |elche|2021-01-01 09:00|7.1        |16.1    |67      |7.1      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.542+0000] {subprocess.py:106} INFO - |elche|2021-01-01 15:00|13.2       |28.4    |32      |13.2     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.544+0000] {subprocess.py:106} INFO - |elche|2021-01-01 22:00|8.0        |17.4    |52      |8.0      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.545+0000] {subprocess.py:106} INFO - |elche|2021-01-02 04:00|5.5        |15.8    |59      |5.5      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.548+0000] {subprocess.py:106} INFO - |elche|2021-01-02 09:00|4.9        |22.8    |55      |4.9      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.550+0000] {subprocess.py:106} INFO - |elche|2021-01-02 15:00|10.5       |29.5    |33      |10.5     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.552+0000] {subprocess.py:106} INFO - |elche|2021-01-02 22:00|6.4        |15.8    |41      |6.4      |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-26T12:20:53.554+0000] {subprocess.py:106} INFO - |elche|2021-01-03 04:00|5.2        |29.6    |46      |5.2      |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-26T12:20:53.555+0000] {subprocess.py:106} INFO - |elche|2021-01-03 09:00|5.3        |23.5    |46      |5.3      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.556+0000] {subprocess.py:106} INFO - |elche|2021-01-03 15:00|12.5       |25.5    |27      |12.5     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.558+0000] {subprocess.py:106} INFO - |elche|2021-01-03 22:00|5.5        |8.6     |50      |5.5      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.560+0000] {subprocess.py:106} INFO - |elche|2021-01-04 04:00|4.8        |11.5    |57      |4.8      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.563+0000] {subprocess.py:106} INFO - |elche|2021-01-04 09:00|4.2        |9.8     |63      |4.2      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.565+0000] {subprocess.py:106} INFO - |elche|2021-01-04 15:00|13.0       |20.6    |30      |13.0     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.568+0000] {subprocess.py:106} INFO - |elche|2021-01-04 22:00|7.5        |15.8    |55      |7.5      |0.0      |Mostly Clear |//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-26T12:20:53.570+0000] {subprocess.py:106} INFO - |elche|2021-01-05 04:00|4.4        |11.8    |68      |4.4      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.571+0000] {subprocess.py:106} INFO - |elche|2021-01-05 09:00|3.5        |20.6    |69      |3.5      |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.580+0000] {subprocess.py:106} INFO - |elche|2021-01-05 15:00|12.4       |8.2     |24      |12.4     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-03-26T12:20:53.581+0000] {subprocess.py:106} INFO - |elche|2021-01-05 22:00|5.6        |8.0     |45      |5.6      |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-03-26T12:20:53.582+0000] {subprocess.py:106} INFO - +-----+----------------+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-03-26T12:20:53.583+0000] {subprocess.py:106} INFO - only showing top 20 rows
[2025-03-26T12:20:53.585+0000] {subprocess.py:106} INFO - 
[2025-03-26T12:20:53.586+0000] {subprocess.py:106} INFO - Error: An error occurred while calling o126.save.
[2025-03-26T12:20:53.588+0000] {subprocess.py:106} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 24) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 1 INSERT INTO daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2021-01-01 09:00',7.1,16.1,67,7.1,0.0,'Sunny','//cdn.weatherapi.com/weather/64x64/day/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.589+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-26T12:20:53.590+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-26T12:20:53.591+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-26T12:20:53.593+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1416)
[2025-03-26T12:20:53.595+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1441)
[2025-03-26T12:20:53.596+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:506)
[2025-03-26T12:20:53.597+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-26T12:20:53.598+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-26T12:20:53.602+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-26T12:20:53.604+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:748)
[2025-03-26T12:20:53.605+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-26T12:20:53.606+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-26T12:20:53.606+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-26T12:20:53.608+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-26T12:20:53.609+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-26T12:20:53.610+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-26T12:20:53.611+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-26T12:20:53.613+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-26T12:20:53.614+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-26T12:20:53.615+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-26T12:20:53.616+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-26T12:20:53.618+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-26T12:20:53.620+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-26T12:20:53.621+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-26T12:20:53.623+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-26T12:20:53.624+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-26T12:20:53.625+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.626+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.
[2025-03-26T12:20:53.627+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-26T12:20:53.628+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-26T12:20:53.629+0000] {subprocess.py:106} INFO - 	... 23 more
[2025-03-26T12:20:53.630+0000] {subprocess.py:106} INFO - 
[2025-03-26T12:20:53.631+0000] {subprocess.py:106} INFO - Driver stacktrace:
[2025-03-26T12:20:53.632+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-03-26T12:20:53.633+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-03-26T12:20:53.634+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-03-26T12:20:53.635+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-26T12:20:53.637+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-26T12:20:53.638+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-26T12:20:53.640+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-03-26T12:20:53.641+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-03-26T12:20:53.641+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-03-26T12:20:53.642+0000] {subprocess.py:106} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-03-26T12:20:53.643+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-03-26T12:20:53.644+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-03-26T12:20:53.645+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-03-26T12:20:53.645+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-03-26T12:20:53.646+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-26T12:20:53.647+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-03-26T12:20:53.647+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-03-26T12:20:53.648+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-03-26T12:20:53.649+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-03-26T12:20:53.650+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2458)
[2025-03-26T12:20:53.650+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1039)
[2025-03-26T12:20:53.652+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-03-26T12:20:53.653+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-03-26T12:20:53.654+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
[2025-03-26T12:20:53.656+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1037)
[2025-03-26T12:20:53.657+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:3516)
[2025-03-26T12:20:53.658+0000] {subprocess.py:106} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-03-26T12:20:53.658+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:4310)
[2025-03-26T12:20:53.659+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-26T12:20:53.660+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-26T12:20:53.661+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-26T12:20:53.662+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-26T12:20:53.663+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-26T12:20:53.664+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:4308)
[2025-03-26T12:20:53.665+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:3516)
[2025-03-26T12:20:53.665+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:903)
[2025-03-26T12:20:53.666+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:70)
[2025-03-26T12:20:53.667+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[2025-03-26T12:20:53.667+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
[2025-03-26T12:20:53.668+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
[2025-03-26T12:20:53.670+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
[2025-03-26T12:20:53.671+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-03-26T12:20:53.672+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-26T12:20:53.673+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-26T12:20:53.673+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-26T12:20:53.674+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-26T12:20:53.675+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-26T12:20:53.676+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-03-26T12:20:53.676+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-03-26T12:20:53.677+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-03-26T12:20:53.678+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-03-26T12:20:53.679+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-03-26T12:20:53.679+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-26T12:20:53.680+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-03-26T12:20:53.681+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-03-26T12:20:53.682+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-26T12:20:53.682+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-26T12:20:53.683+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-03-26T12:20:53.684+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-03-26T12:20:53.684+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-03-26T12:20:53.686+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-03-26T12:20:53.687+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-03-26T12:20:53.689+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-03-26T12:20:53.690+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-03-26T12:20:53.691+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-03-26T12:20:53.692+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
[2025-03-26T12:20:53.693+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-26T12:20:53.694+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-26T12:20:53.695+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-26T12:20:53.696+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-26T12:20:53.697+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-26T12:20:53.698+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-26T12:20:53.699+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-26T12:20:53.700+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-26T12:20:53.701+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-26T12:20:53.703+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-26T12:20:53.704+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-26T12:20:53.705+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-26T12:20:53.706+0000] {subprocess.py:106} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 1 INSERT INTO daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2021-01-01 09:00',7.1,16.1,67,7.1,0.0,'Sunny','//cdn.weatherapi.com/weather/64x64/day/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.707+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-26T12:20:53.708+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-26T12:20:53.709+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-26T12:20:53.710+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1416)
[2025-03-26T12:20:53.711+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1441)
[2025-03-26T12:20:53.712+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:506)
[2025-03-26T12:20:53.713+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-26T12:20:53.714+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-26T12:20:53.716+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-26T12:20:53.717+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:748)
[2025-03-26T12:20:53.718+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-26T12:20:53.719+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-26T12:20:53.721+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-26T12:20:53.722+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-26T12:20:53.723+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-26T12:20:53.724+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-26T12:20:53.725+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-26T12:20:53.726+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-26T12:20:53.727+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-26T12:20:53.728+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-26T12:20:53.729+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-26T12:20:53.730+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-26T12:20:53.731+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-26T12:20:53.732+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-26T12:20:53.733+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-26T12:20:53.734+0000] {subprocess.py:106} INFO - 	... 1 more
[2025-03-26T12:20:53.735+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-26T12:20:53.737+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2021-01-01 09:00) already exists.
[2025-03-26T12:20:53.738+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-26T12:20:53.739+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-26T12:20:53.740+0000] {subprocess.py:106} INFO - 	... 23 more
[2025-03-26T12:20:53.741+0000] {subprocess.py:106} INFO - 
[2025-03-26T12:20:54.156+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-26T12:20:54.176+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T12:20:54.177+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=historical_weather_etl, task_id=run_historical_script, run_id=manual__2025-03-26T12:20:34.870301+00:00, execution_date=20250326T122034, start_date=20250326T122037, end_date=20250326T122054
[2025-03-26T12:20:54.199+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-26T12:20:54.200+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-26T12:20:54.202+0000] {logging_mixin.py:190} INFO - Dag name:historical_weather_etl queued_at:2025-03-26 12:20:34.880595+00:00
[2025-03-26T12:20:54.203+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-26T12:20:54.221+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T12:20:54.236+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T12:20:54.239+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
