[2025-04-22T06:20:14.656+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T06:20:14.911+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-18T07:00:00+00:00 [queued]>
[2025-04-22T06:20:14.939+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-18T07:00:00+00:00 [queued]>
[2025-04-22T06:20:14.941+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-22T06:20:14.978+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_minio_script> on 2025-04-18 07:00:00+00:00
[2025-04-22T06:20:15.002+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_minio_script', 'scheduled__2025-04-18T07:00:00+00:00', '--job-id', '343', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp2b854kt8']
[2025-04-22T06:20:15.007+0000] {standard_task_runner.py:105} INFO - Job 343: Subtask run_minio_script
[2025-04-22T06:20:14.996+0000] {standard_task_runner.py:72} INFO - Started process 391 to run task
[2025-04-22T06:20:15.124+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-18T07:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-04-22T06:20:15.321+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_minio_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T07:00:00+00:00'
[2025-04-22T06:20:15.325+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-22T06:20:15.326+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-22T06:20:15.328+0000] {logging_mixin.py:190} INFO - Current task name:run_minio_script state:running start_date:2025-04-22 06:20:14.913889+00:00
[2025-04-22T06:20:15.329+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-04-22T06:20:15.330+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T06:20:15.334+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-22T06:20:15.343+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/minio.py']
[2025-04-22T06:20:15.371+0000] {subprocess.py:99} INFO - Output:
[2025-04-22T06:20:19.994+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-04-22T06:20:19.998+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-22T06:20:20.333+0000] {subprocess.py:106} INFO - 25/04/22 06:20:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-22T06:20:45.370+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-04-22T06:20:45.375+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-22T06:20:45.400+0000] {process_utils.py:132} INFO - Sending 15 to group 391. PIDs of all processes in the group: [395, 411, 667, 732, 761, 767, 772, 779, 782, 790, 798, 801, 689, 693, 694, 706, 712, 713, 714, 718, 391]
[2025-04-22T06:20:45.403+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 391
[2025-04-22T06:20:45.404+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-22T06:20:45.451+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.9/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/***/.local/lib/python3.9/site-packages/***/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-04-22T06:20:45.454+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-04-22T06:20:45.479+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-22T06:20:45.486+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-22T06:20:45.488+0000] {logging_mixin.py:190} INFO - Task start:2025-04-22 06:20:14.913889+00:00 end:2025-04-22 06:20:45.485611+00:00 duration:30.571722
[2025-04-22T06:20:45.489+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_minio_script> dag:<DAG: daily_weather_etl> dagrun:<DagRun daily_weather_etl @ 2025-04-18 07:00:00+00:00: scheduled__2025-04-18T07:00:00+00:00, state:running, queued_at: 2025-04-22 06:19:54.622218+00:00. externally triggered: False>
[2025-04-22T06:20:45.490+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-04-22T06:20:45.492+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_etl, task_id=run_minio_script, run_id=scheduled__2025-04-18T07:00:00+00:00, execution_date=20250418T070000, start_date=20250422T062014, end_date=20250422T062045
[2025-04-22T06:20:45.506+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T06:20:45.508+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 343 for task run_minio_script ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-18T07:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_minio_script', 'dag_id': 'daily_weather_etl', 'run_id': 'scheduled__2025-04-18T07:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 22, 6, 20, 14, 913889, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 22, 6, 20, 45, 485611, tzinfo=Timezone('UTC')), 'duration': 30}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 391)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-18T07:00:00+00:00, -1) is not present in table "task_instance".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 328, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3434, in handle_failure
    _handle_failure(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1244, in _handle_failure
    TaskInstance.save_to_db(task_instance, session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3402, in save_to_db
    ti.get_dagrun().refresh_from_db()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 57, in create_session
    session.commit()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-18T07:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_minio_script', 'dag_id': 'daily_weather_etl', 'run_id': 'scheduled__2025-04-18T07:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 22, 6, 20, 14, 913889, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 22, 6, 20, 45, 485611, tzinfo=Timezone('UTC')), 'duration': 30}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-04-22T06:20:45.581+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=694, status='terminated', started='06:20:31') (694) terminated with exit code None
[2025-04-22T06:20:45.588+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=798, status='terminated', started='06:20:32') (798) terminated with exit code None
[2025-04-22T06:20:45.592+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=779, status='terminated', started='06:20:32') (779) terminated with exit code None
[2025-04-22T06:20:45.595+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=693, status='terminated', started='06:20:31') (693) terminated with exit code None
[2025-04-22T06:20:45.597+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=782, status='terminated', started='06:20:32') (782) terminated with exit code None
[2025-04-22T06:20:45.599+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=706, status='terminated', started='06:20:31') (706) terminated with exit code None
[2025-04-22T06:20:45.662+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=732, status='terminated', started='06:20:31') (732) terminated with exit code None
[2025-04-22T06:20:45.663+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=667, status='terminated', started='06:20:28') (667) terminated with exit code None
[2025-04-22T06:20:45.665+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=689, status='terminated', started='06:20:31') (689) terminated with exit code None
[2025-04-22T06:20:45.670+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=712, status='terminated', started='06:20:31') (712) terminated with exit code None
[2025-04-22T06:20:45.724+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=713, status='terminated', started='06:20:31') (713) terminated with exit code None
[2025-04-22T06:20:45.731+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=767, status='terminated', started='06:20:32') (767) terminated with exit code None
[2025-04-22T06:20:45.738+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=801, status='terminated', started='06:20:32') (801) terminated with exit code None
[2025-04-22T06:20:45.740+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=761, status='terminated', started='06:20:32') (761) terminated with exit code None
[2025-04-22T06:20:45.750+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=718, status='terminated', started='06:20:31') (718) terminated with exit code None
[2025-04-22T06:20:45.751+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=391, status='terminated', exitcode=1, started='06:20:14') (391) terminated with exit code 1
[2025-04-22T06:20:45.754+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=772, status='terminated', started='06:20:32') (772) terminated with exit code None
[2025-04-22T06:20:45.756+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=395, status='terminated', started='06:20:14') (395) terminated with exit code None
[2025-04-22T06:20:45.758+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=714, status='terminated', started='06:20:31') (714) terminated with exit code None
[2025-04-22T06:20:45.760+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=790, status='terminated', started='06:20:32') (790) terminated with exit code None
[2025-04-22T06:20:46.313+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=411, status='terminated', started='06:20:16') (411) terminated with exit code None
[2025-04-22T06:21:07.464+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T06:21:07.653+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-18T07:00:00+00:00 [queued]>
[2025-04-22T06:21:07.669+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-18T07:00:00+00:00 [queued]>
[2025-04-22T06:21:07.670+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-22T06:21:07.685+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_minio_script> on 2025-04-18 07:00:00+00:00
[2025-04-22T06:21:07.693+0000] {standard_task_runner.py:72} INFO - Started process 3708 to run task
[2025-04-22T06:21:07.699+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_minio_script', 'scheduled__2025-04-18T07:00:00+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp_w_lltva']
[2025-04-22T06:21:07.702+0000] {standard_task_runner.py:105} INFO - Job 346: Subtask run_minio_script
[2025-04-22T06:21:07.774+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-18T07:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-04-22T06:21:07.884+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_minio_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-18T07:00:00+00:00'
[2025-04-22T06:21:07.886+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-22T06:21:07.887+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-22T06:21:07.888+0000] {logging_mixin.py:190} INFO - Current task name:run_minio_script state:running start_date:2025-04-22 06:21:07.654858+00:00
[2025-04-22T06:21:07.890+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-04-22T06:21:07.891+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-22T06:21:07.892+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-22T06:21:07.893+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/minio.py']
[2025-04-22T06:21:07.905+0000] {subprocess.py:99} INFO - Output:
[2025-04-22T06:21:10.652+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-04-22T06:21:10.654+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-22T06:21:10.853+0000] {subprocess.py:106} INFO - 25/04/22 06:21:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-22T06:21:27.999+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 8) / 8]                                                                                [Stage 58:>                                                         (0 + 1) / 1]                                                                                +-----+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.000+0000] {subprocess.py:106} INFO - |city |local_time         |temperature|wind_kph|humidity|feelslike|precip_mm|text         |
[2025-04-22T06:21:28.004+0000] {subprocess.py:106} INFO - +-----+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.005+0000] {subprocess.py:106} INFO - |elche|2025-04-20 04:00:00|12.4       |9.8     |50      |12.4     |0.0      |Sunny        |
[2025-04-22T06:21:28.006+0000] {subprocess.py:106} INFO - |elche|2025-04-20 09:00:00|13.5       |9.8     |48      |13.5     |0.0      |Partly Cloudy|
[2025-04-22T06:21:28.007+0000] {subprocess.py:106} INFO - |elche|2025-04-20 15:00:00|14.2       |20.6    |57      |14.2     |1.7      |Light Rain   |
[2025-04-22T06:21:28.009+0000] {subprocess.py:106} INFO - |elche|2025-04-20 22:00:00|16.2       |12.1    |43      |16.2     |0.0      |Sunny        |
[2025-04-22T06:21:28.010+0000] {subprocess.py:106} INFO - +-----+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.011+0000] {subprocess.py:106} INFO - 
[2025-04-22T06:21:28.011+0000] {subprocess.py:106} INFO - +------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.013+0000] {subprocess.py:106} INFO - |city  |local_time         |temperature|wind_kph|humidity|feelslike|precip_mm|text         |
[2025-04-22T06:21:28.014+0000] {subprocess.py:106} INFO - +------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.015+0000] {subprocess.py:106} INFO - |madrid|2025-04-20 04:00:00|6.2        |17.9    |89      |6.2      |0.1      |Light Drizzle|
[2025-04-22T06:21:28.016+0000] {subprocess.py:106} INFO - |madrid|2025-04-20 09:00:00|6.4        |10.9    |93      |6.4      |0.0      |Mostly Clear |
[2025-04-22T06:21:28.017+0000] {subprocess.py:106} INFO - |madrid|2025-04-20 15:00:00|13.0       |15.3    |46      |13.0     |0.0      |Cloudy       |
[2025-04-22T06:21:28.018+0000] {subprocess.py:106} INFO - |madrid|2025-04-20 22:00:00|10.7       |3.2     |71      |10.7     |0.0      |Partly Cloudy|
[2025-04-22T06:21:28.020+0000] {subprocess.py:106} INFO - +------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.021+0000] {subprocess.py:106} INFO - 
[2025-04-22T06:21:28.022+0000] {subprocess.py:106} INFO - +--------------------+-------------------+-----------+--------+--------+---------+---------+----------------+
[2025-04-22T06:21:28.024+0000] {subprocess.py:106} INFO - |city                |local_time         |temperature|wind_kph|humidity|feelslike|precip_mm|text            |
[2025-04-22T06:21:28.025+0000] {subprocess.py:106} INFO - +--------------------+-------------------+-----------+--------+--------+---------+---------+----------------+
[2025-04-22T06:21:28.026+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 04:00:00|11.8       |7.7     |54      |11.8     |0.0      |Sunny           |
[2025-04-22T06:21:28.027+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 09:00:00|13.6       |8.3     |50      |13.6     |0.0      |Cloudy          |
[2025-04-22T06:21:28.028+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 15:00:00|14.9       |18.2    |58      |14.9     |0.9      |Moderate Drizzle|
[2025-04-22T06:21:28.029+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 22:00:00|14.8       |6.2     |48      |14.8     |0.0      |Sunny           |
[2025-04-22T06:21:28.030+0000] {subprocess.py:106} INFO - +--------------------+-------------------+-----------+--------+--------+---------+---------+----------------+
[2025-04-22T06:21:28.031+0000] {subprocess.py:106} INFO - 
[2025-04-22T06:21:28.032+0000] {subprocess.py:106} INFO - +----------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.033+0000] {subprocess.py:106} INFO - |city      |local_time         |temperature|wind_kph|humidity|feelslike|precip_mm|text         |
[2025-04-22T06:21:28.034+0000] {subprocess.py:106} INFO - +----------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.035+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-20 04:00:00|12.0       |5.7     |73      |12.0     |0.0      |Sunny        |
[2025-04-22T06:21:28.036+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-20 09:00:00|13.2       |13.5    |65      |13.2     |0.0      |Cloudy       |
[2025-04-22T06:21:28.037+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-20 15:00:00|18.4       |13.2    |42      |18.4     |0.2      |Light Drizzle|
[2025-04-22T06:21:28.038+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-20 22:00:00|15.0       |9.7     |64      |15.0     |0.0      |Sunny        |
[2025-04-22T06:21:28.039+0000] {subprocess.py:106} INFO - +----------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.040+0000] {subprocess.py:106} INFO - 
[2025-04-22T06:21:28.041+0000] {subprocess.py:106} INFO - +--------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.043+0000] {subprocess.py:106} INFO - |city    |local_time         |temperature|wind_kph|humidity|feelslike|precip_mm|text         |
[2025-04-22T06:21:28.044+0000] {subprocess.py:106} INFO - +--------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.045+0000] {subprocess.py:106} INFO - |valencia|2025-04-20 04:00:00|13.2       |13.3    |53      |13.2     |0.0      |Sunny        |
[2025-04-22T06:21:28.046+0000] {subprocess.py:106} INFO - |valencia|2025-04-20 09:00:00|13.3       |13.5    |51      |13.3     |0.0      |Mostly Clear |
[2025-04-22T06:21:28.047+0000] {subprocess.py:106} INFO - |valencia|2025-04-20 15:00:00|20.9       |6.7     |28      |20.9     |0.0      |Partly Cloudy|
[2025-04-22T06:21:28.048+0000] {subprocess.py:106} INFO - |valencia|2025-04-20 22:00:00|16.7       |6.6     |49      |16.7     |0.0      |Mostly Clear |
[2025-04-22T06:21:28.049+0000] {subprocess.py:106} INFO - +--------+-------------------+-----------+--------+--------+---------+---------+-------------+
[2025-04-22T06:21:28.050+0000] {subprocess.py:106} INFO - 
[2025-04-22T06:21:28.051+0000] {subprocess.py:106} INFO - +--------------------+-------------------+-----------+--------+--------+---------+---------+----------------+
[2025-04-22T06:21:28.052+0000] {subprocess.py:106} INFO - |                city|         local_time|temperature|wind_kph|humidity|feelslike|precip_mm|            text|
[2025-04-22T06:21:28.053+0000] {subprocess.py:106} INFO - +--------------------+-------------------+-----------+--------+--------+---------+---------+----------------+
[2025-04-22T06:21:28.054+0000] {subprocess.py:106} INFO - |               elche|2025-04-20 04:00:00|       12.4|     9.8|      50|     12.4|      0.0|           Sunny|
[2025-04-22T06:21:28.055+0000] {subprocess.py:106} INFO - |               elche|2025-04-20 09:00:00|       13.5|     9.8|      48|     13.5|      0.0|   Partly Cloudy|
[2025-04-22T06:21:28.056+0000] {subprocess.py:106} INFO - |               elche|2025-04-20 15:00:00|       14.2|    20.6|      57|     14.2|      1.7|      Light Rain|
[2025-04-22T06:21:28.057+0000] {subprocess.py:106} INFO - |               elche|2025-04-20 22:00:00|       16.2|    12.1|      43|     16.2|      0.0|           Sunny|
[2025-04-22T06:21:28.058+0000] {subprocess.py:106} INFO - |              madrid|2025-04-20 04:00:00|        6.2|    17.9|      89|      6.2|      0.1|   Light Drizzle|
[2025-04-22T06:21:28.058+0000] {subprocess.py:106} INFO - |              madrid|2025-04-20 09:00:00|        6.4|    10.9|      93|      6.4|      0.0|    Mostly Clear|
[2025-04-22T06:21:28.059+0000] {subprocess.py:106} INFO - |              madrid|2025-04-20 15:00:00|       13.0|    15.3|      46|     13.0|      0.0|          Cloudy|
[2025-04-22T06:21:28.060+0000] {subprocess.py:106} INFO - |              madrid|2025-04-20 22:00:00|       10.7|     3.2|      71|     10.7|      0.0|   Partly Cloudy|
[2025-04-22T06:21:28.061+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 04:00:00|       11.8|     7.7|      54|     11.8|      0.0|           Sunny|
[2025-04-22T06:21:28.062+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 09:00:00|       13.6|     8.3|      50|     13.6|      0.0|          Cloudy|
[2025-04-22T06:21:28.063+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 15:00:00|       14.9|    18.2|      58|     14.9|      0.9|Moderate Drizzle|
[2025-04-22T06:21:28.064+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-20 22:00:00|       14.8|     6.2|      48|     14.8|      0.0|           Sunny|
[2025-04-22T06:21:28.065+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-20 04:00:00|       12.0|     5.7|      73|     12.0|      0.0|           Sunny|
[2025-04-22T06:21:28.066+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-20 09:00:00|       13.2|    13.5|      65|     13.2|      0.0|          Cloudy|
[2025-04-22T06:21:28.066+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-20 15:00:00|       18.4|    13.2|      42|     18.4|      0.2|   Light Drizzle|
[2025-04-22T06:21:28.067+0000] {subprocess.py:106} INFO - |          torrevieja|2025-04-20 22:00:00|       15.0|     9.7|      64|     15.0|      0.0|           Sunny|
[2025-04-22T06:21:28.068+0000] {subprocess.py:106} INFO - |            valencia|2025-04-20 04:00:00|       13.2|    13.3|      53|     13.2|      0.0|           Sunny|
[2025-04-22T06:21:28.069+0000] {subprocess.py:106} INFO - |            valencia|2025-04-20 09:00:00|       13.3|    13.5|      51|     13.3|      0.0|    Mostly Clear|
[2025-04-22T06:21:28.070+0000] {subprocess.py:106} INFO - |            valencia|2025-04-20 15:00:00|       20.9|     6.7|      28|     20.9|      0.0|   Partly Cloudy|
[2025-04-22T06:21:28.071+0000] {subprocess.py:106} INFO - |            valencia|2025-04-20 22:00:00|       16.7|     6.6|      49|     16.7|      0.0|    Mostly Clear|
[2025-04-22T06:21:28.072+0000] {subprocess.py:106} INFO - +--------------------+-------------------+-----------+--------+--------+---------+---------+----------------+
[2025-04-22T06:21:28.073+0000] {subprocess.py:106} INFO - 
[2025-04-22T06:21:28.075+0000] {subprocess.py:106} INFO - Nombre de la carpeta: 2025-04-20
[2025-04-22T06:21:28.076+0000] {subprocess.py:106} INFO - Archivo Parquet generado: /tmp/tmpdehvl_qy/2025-04-20/part-00000-7adea1f1-781b-4db2-8d1a-4b332a3cf0ad-c000.snappy.parquet
[2025-04-22T06:21:28.077+0000] {subprocess.py:106} INFO - Archivo subido correctamente a MinIO en: 2025-04-20/2025-04-20.parquet
[2025-04-22T06:21:28.559+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-22T06:21:28.583+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-22T06:21:28.584+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_minio_script, run_id=scheduled__2025-04-18T07:00:00+00:00, execution_date=20250418T070000, start_date=20250422T062107, end_date=20250422T062128
[2025-04-22T06:21:28.607+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-22T06:21:28.608+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-22T06:21:28.609+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-04-22 06:20:56.552931+00:00
[2025-04-22T06:21:28.609+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-04-22T06:21:28.626+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-22T06:21:28.650+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-22T06:21:28.653+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
