[2025-04-07T06:35:29.974+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T06:35:30.174+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-05T07:00:00+00:00 [queued]>
[2025-04-07T06:35:30.192+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-05T07:00:00+00:00 [queued]>
[2025-04-07T06:35:30.209+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-07T06:35:30.235+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_minio_script> on 2025-04-05 07:00:00+00:00
[2025-04-07T06:35:30.245+0000] {standard_task_runner.py:72} INFO - Started process 391 to run task
[2025-04-07T06:35:30.251+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_minio_script', 'scheduled__2025-04-05T07:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp9d646t76']
[2025-04-07T06:35:30.254+0000] {standard_task_runner.py:105} INFO - Job 227: Subtask run_minio_script
[2025-04-07T06:35:30.332+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_minio_script scheduled__2025-04-05T07:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-04-07T06:35:30.486+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_minio_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T07:00:00+00:00'
[2025-04-07T06:35:30.490+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-07T06:35:30.491+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-07T06:35:30.493+0000] {logging_mixin.py:190} INFO - Current task name:run_minio_script state:running start_date:2025-04-07 06:35:30.175634+00:00
[2025-04-07T06:35:30.494+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-04-07T06:35:30.495+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-07T06:35:30.497+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-07T06:35:30.499+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/minio.py']
[2025-04-07T06:35:30.517+0000] {subprocess.py:99} INFO - Output:
[2025-04-07T06:35:35.044+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-04-07T06:35:35.046+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-07T06:35:35.328+0000] {subprocess.py:106} INFO - 25/04/07 06:35:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-07T06:36:10.233+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 8) / 8][Stage 0:=======>                                                   (1 + 7) / 8]                                                                                [Stage 1:=======>                                                   (1 + 7) / 8][Stage 1:======================>                                    (3 + 5) / 8]                                                                                [Stage 2:============================================>              (6 + 2) / 8]                                                                                [Stage 6:=======>                                                   (1 + 7) / 8][Stage 7:====================================>                      (5 + 3) / 8]                                                                                [Stage 8:============================================>              (6 + 2) / 8]                                                                                +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.236+0000] {subprocess.py:106} INFO - |city |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T06:36:10.238+0000] {subprocess.py:106} INFO - +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.240+0000] {subprocess.py:106} INFO - |elche|2025-04-05|22:00|17.6       |5.1     |59      |17.6     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:10.241+0000] {subprocess.py:106} INFO - |elche|2025-04-05|15:00|24.5       |16.0    |22      |24.5     |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:10.243+0000] {subprocess.py:106} INFO - |elche|2025-04-05|09:00|15.4       |11.7    |61      |15.4     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.244+0000] {subprocess.py:106} INFO - |elche|2025-04-05|04:00|16.1       |15.7    |58      |16.1     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.246+0000] {subprocess.py:106} INFO - +-----+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.247+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:10.249+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.251+0000] {subprocess.py:106} INFO - |city  |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T06:36:10.254+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.256+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|09:00|8.8        |9.7     |91      |8.8      |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:10.258+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|15:00|14.3       |7.8     |58      |14.3     |0.1      |Light Drizzle|//cdn.weatherapi.com/weather/64x64/day/176.png|
[2025-04-07T06:36:10.277+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|04:00|9.2        |12.5    |93      |9.2      |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:10.279+0000] {subprocess.py:106} INFO - |madrid|2025-04-05|22:00|11.2       |6.6     |74      |11.2     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:10.280+0000] {subprocess.py:106} INFO - +------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.282+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:10.283+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:10.285+0000] {subprocess.py:106} INFO - |city                |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text        |icon                                          |
[2025-04-07T06:36:10.287+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:10.288+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|09:00|15.6       |7.9     |60      |15.6     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.292+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|15:00|23.9       |16.5    |24      |23.9     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.294+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|04:00|13.6       |4.9     |81      |13.6     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.296+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-04-05|22:00|16.5       |3.4     |68      |16.5     |0.0      |Mostly Clear|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:10.298+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:10.301+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:10.303+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.305+0000] {subprocess.py:106} INFO - |city      |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text         |icon                                          |
[2025-04-07T06:36:10.307+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.309+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|04:00|14.0       |4.9     |98      |14.0     |0.0      |Partly Cloudy|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:10.310+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|09:00|15.3       |12.1    |72      |15.3     |0.0      |Sunny        |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.314+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|15:00|22.8       |12.2    |36      |22.8     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:10.315+0000] {subprocess.py:106} INFO - |torrevieja|2025-04-05|22:00|15.7       |5.8     |72      |15.7     |0.0      |Cloudy       |//cdn.weatherapi.com/weather/64x64/day/119.png|
[2025-04-07T06:36:10.316+0000] {subprocess.py:106} INFO - +----------+----------+-----+-----------+--------+--------+---------+---------+-------------+----------------------------------------------+
[2025-04-07T06:36:10.319+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:10.321+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:10.322+0000] {subprocess.py:106} INFO - |city    |date      |time |temperature|wind_kph|humidity|feelslike|precip_mm|text        |icon                                          |
[2025-04-07T06:36:10.324+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:10.325+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|04:00|13.3       |7.3     |87      |13.3     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.328+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|22:00|17.2       |8.1     |58      |17.2     |0.0      |Mostly Clear|//cdn.weatherapi.com/weather/64x64/day/116.png|
[2025-04-07T06:36:10.330+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|09:00|14.4       |15.8    |66      |14.4     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.331+0000] {subprocess.py:106} INFO - |valencia|2025-04-05|15:00|23.3       |12.1    |27      |23.3     |0.0      |Sunny       |//cdn.weatherapi.com/weather/64x64/day/113.png|
[2025-04-07T06:36:10.333+0000] {subprocess.py:106} INFO - +--------+----------+-----+-----------+--------+--------+---------+---------+------------+----------------------------------------------+
[2025-04-07T06:36:10.334+0000] {subprocess.py:106} INFO - 
[2025-04-07T06:36:10.807+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-04-07T06:36:10.842+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-07T06:36:10.875+0000] {process_utils.py:132} INFO - Sending 15 to group 391. PIDs of all processes in the group: [393, 415, 669, 742, 757, 761, 765, 769, 777, 778, 782, 799, 683, 687, 696, 706, 715, 722, 730, 735, 391]
[2025-04-07T06:36:10.877+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 391
[2025-04-07T06:36:10.880+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-07T06:36:10.976+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.9/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 64, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 237, in worker
    _run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 50, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/cli/celery_command.py", line 230, in run_celery_worker
    celery_app.worker_main(options)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/***/.local/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/***/.local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
  File "/home/***/.local/lib/python3.9/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.9/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "/home/***/.local/lib/python3.9/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 139, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
  File "/home/***/.local/lib/python3.9/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 171, in _execute_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.9/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.9/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.9/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.9/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/***/.local/lib/python3.9/site-packages/***/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/***/.local/lib/python3.9/site-packages/***/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/***/.local/lib/python3.9/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-04-07T06:36:11.006+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-04-07T06:36:11.042+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-07T06:36:11.059+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-07T06:36:11.073+0000] {logging_mixin.py:190} INFO - Task start:2025-04-07 06:35:30.175634+00:00 end:2025-04-07 06:36:11.057944+00:00 duration:40.88231
[2025-04-07T06:36:11.102+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_minio_script> dag:<DAG: daily_weather_etl> dagrun:<DagRun daily_weather_etl @ 2025-04-05 07:00:00+00:00: scheduled__2025-04-05T07:00:00+00:00, state:running, queued_at: 2025-04-07 06:34:36.819994+00:00. externally triggered: False>
[2025-04-07T06:36:11.106+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-04-07T06:36:11.118+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_etl, task_id=run_minio_script, run_id=scheduled__2025-04-05T07:00:00+00:00, execution_date=20250405T070000, start_date=20250407T063530, end_date=20250407T063611
[2025-04-07T06:36:11.232+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-07T06:36:11.256+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 227 for task run_minio_script ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-05T07:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_minio_script', 'dag_id': 'daily_weather_etl', 'run_id': 'scheduled__2025-04-05T07:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 7, 6, 35, 30, 175634, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 7, 6, 36, 11, 57944, tzinfo=Timezone('UTC')), 'duration': 40}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 391)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-05T07:00:00+00:00, -1) is not present in table "task_instance".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 328, in _run_raw_task
    ti.handle_failure(e, test_mode, context, session=session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3434, in handle_failure
    _handle_failure(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1244, in _handle_failure
    TaskInstance.save_to_db(task_instance, session)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3402, in save_to_db
    ti.get_dagrun().refresh_from_db()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 57, in create_session
    session.commit()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(daily_weather_etl, run_minio_script, scheduled__2025-04-05T07:00:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'run_minio_script', 'dag_id': 'daily_weather_etl', 'run_id': 'scheduled__2025-04-05T07:00:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2025, 4, 7, 6, 35, 30, 175634, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 4, 7, 6, 36, 11, 57944, tzinfo=Timezone('UTC')), 'duration': 40}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-04-07T06:36:11.601+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=393, status='terminated', started='06:35:30') (393) terminated with exit code None
[2025-04-07T06:36:11.603+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=782, status='terminated', started='06:35:53') (782) terminated with exit code None
[2025-04-07T06:36:11.607+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=735, status='terminated', started='06:35:51') (735) terminated with exit code None
[2025-04-07T06:36:11.611+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=778, status='terminated', started='06:35:53') (778) terminated with exit code None
[2025-04-07T06:36:11.618+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=706, status='terminated', started='06:35:51') (706) terminated with exit code None
[2025-04-07T06:36:11.622+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=730, status='terminated', started='06:35:51') (730) terminated with exit code None
[2025-04-07T06:36:11.625+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=687, status='terminated', started='06:35:51') (687) terminated with exit code None
[2025-04-07T06:36:11.700+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=777, status='terminated', started='06:35:53') (777) terminated with exit code None
[2025-04-07T06:36:11.719+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=757, status='terminated', started='06:35:53') (757) terminated with exit code None
[2025-04-07T06:36:11.721+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=765, status='terminated', started='06:35:53') (765) terminated with exit code None
[2025-04-07T06:36:11.817+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=391, status='terminated', exitcode=1, started='06:35:30') (391) terminated with exit code 1
[2025-04-07T06:36:11.820+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=761, status='terminated', started='06:35:53') (761) terminated with exit code None
[2025-04-07T06:36:11.822+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=799, status='terminated', started='06:35:53') (799) terminated with exit code None
[2025-04-07T06:36:11.825+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=722, status='terminated', started='06:35:51') (722) terminated with exit code None
[2025-04-07T06:36:11.831+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=696, status='terminated', started='06:35:51') (696) terminated with exit code None
[2025-04-07T06:36:11.836+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=769, status='terminated', started='06:35:53') (769) terminated with exit code None
[2025-04-07T06:36:11.838+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=669, status='terminated', started='06:35:49') (669) terminated with exit code None
[2025-04-07T06:36:11.842+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=715, status='terminated', started='06:35:51') (715) terminated with exit code None
[2025-04-07T06:36:11.942+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=683, status='terminated', started='06:35:51') (683) terminated with exit code None
[2025-04-07T06:36:11.944+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=742, status='terminated', started='06:35:51') (742) terminated with exit code None
[2025-04-07T06:36:12.449+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=415, status='terminated', started='06:35:32') (415) terminated with exit code None
