[2025-03-28T08:13:42.216+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T08:13:42.351+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-27T08:00:00+00:00 [queued]>
[2025-03-28T08:13:42.364+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-27T08:00:00+00:00 [queued]>
[2025-03-28T08:13:42.365+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-28T08:13:42.378+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_postgres_script> on 2025-03-27 08:00:00+00:00
[2025-03-28T08:13:42.385+0000] {standard_task_runner.py:72} INFO - Started process 721 to run task
[2025-03-28T08:13:42.389+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_postgres_script', 'scheduled__2025-03-27T08:00:00+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpdw54g5l7']
[2025-03-28T08:13:42.391+0000] {standard_task_runner.py:105} INFO - Job 139: Subtask run_postgres_script
[2025-03-28T08:13:42.437+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-27T08:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-03-28T08:13:42.507+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_postgres_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T08:00:00+00:00'
[2025-03-28T08:13:42.509+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-28T08:13:42.510+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-28T08:13:42.511+0000] {logging_mixin.py:190} INFO - Current task name:run_postgres_script state:running start_date:2025-03-28 08:13:42.352955+00:00
[2025-03-28T08:13:42.512+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-28T08:13:42.512+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-28T08:13:42.514+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-28T08:13:42.515+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/postgres.py']
[2025-03-28T08:13:42.526+0000] {subprocess.py:99} INFO - Output:
[2025-03-28T08:13:45.061+0000] {subprocess.py:106} INFO - 25/03/28 08:13:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-28T08:13:45.219+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-28T08:13:45.220+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-28T08:13:52.121+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                25/03/28 08:13:52 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
[2025-03-28T08:13:52.122+0000] {subprocess.py:106} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.123+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-28T08:13:52.127+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-28T08:13:52.129+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-28T08:13:52.130+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-28T08:13:52.131+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-28T08:13:52.133+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-28T08:13:52.134+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-28T08:13:52.135+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-28T08:13:52.137+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-28T08:13:52.138+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-28T08:13:52.139+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-28T08:13:52.141+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-28T08:13:52.144+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-28T08:13:52.145+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-28T08:13:52.146+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-28T08:13:52.147+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-28T08:13:52.149+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-28T08:13:52.151+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-28T08:13:52.152+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-28T08:13:52.154+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-28T08:13:52.155+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-28T08:13:52.157+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-28T08:13:52.162+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-28T08:13:52.164+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-28T08:13:52.165+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.166+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-28T08:13:52.167+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-28T08:13:52.168+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-28T08:13:52.169+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-28T08:13:52.170+0000] {subprocess.py:106} INFO - 25/03/28 08:13:52 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.171+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-28T08:13:52.173+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-28T08:13:52.174+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-28T08:13:52.178+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-28T08:13:52.179+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-28T08:13:52.180+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-28T08:13:52.181+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-28T08:13:52.182+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-28T08:13:52.183+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-28T08:13:52.184+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-28T08:13:52.185+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-28T08:13:52.186+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-28T08:13:52.187+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-28T08:13:52.189+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-28T08:13:52.190+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-28T08:13:52.193+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-28T08:13:52.195+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-28T08:13:52.196+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-28T08:13:52.197+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-28T08:13:52.199+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-28T08:13:52.200+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-28T08:13:52.201+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-28T08:13:52.202+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-28T08:13:52.203+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-28T08:13:52.204+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.205+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-28T08:13:52.207+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-28T08:13:52.209+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-28T08:13:52.211+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-28T08:13:52.212+0000] {subprocess.py:106} INFO - 
[2025-03-28T08:13:52.214+0000] {subprocess.py:106} INFO - 25/03/28 08:13:52 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
[2025-03-28T08:13:52.589+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-28T08:13:52.592+0000] {subprocess.py:106} INFO - |                city|      local_time|temperature|wind_kph|humidity|feelslike|precip_mm| text|                icon|
[2025-03-28T08:13:52.595+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-28T08:13:52.597+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 04:00|       10.2|     3.2|      77|     10.6|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.598+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 09:00|       14.5|     4.0|      56|     15.1|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.599+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 15:00|       19.0|     4.3|      38|     19.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.602+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 22:00|       12.9|    10.1|      83|     12.1|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.604+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 04:00|        6.8|     5.8|      70|      5.9|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.607+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 09:00|        7.9|     5.4|      66|      7.2|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.612+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 15:00|       15.4|     5.4|      39|     15.4|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.616+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 22:00|       11.5|     6.5|      52|     11.1|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.619+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 04:00|       11.6|     4.7|      68|     11.6|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.623+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 09:00|       14.5|     4.7|      59|     15.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.627+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 15:00|       16.5|    16.6|      60|     16.5|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.628+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 22:00|       13.4|     6.5|      80|     13.3|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.630+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 04:00|       11.9|     7.2|      79|     11.4|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.632+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 09:00|       14.0|     6.8|      66|     14.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.633+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 15:00|       18.5|    15.1|      50|     18.5|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-28T08:13:52.634+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 22:00|       14.2|    11.5|      76|     13.5|      0.0|Clear|//cdn.weatherapi....|
[2025-03-28T08:13:52.635+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-28T08:13:52.636+0000] {subprocess.py:106} INFO - 
[2025-03-28T08:13:52.638+0000] {subprocess.py:106} INFO - Error: An error occurred while calling o43.save.
[2025-03-28T08:13:52.639+0000] {subprocess.py:106} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.640+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-28T08:13:52.643+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-28T08:13:52.648+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-28T08:13:52.651+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-28T08:13:52.652+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-28T08:13:52.654+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-28T08:13:52.656+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-28T08:13:52.658+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-28T08:13:52.660+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-28T08:13:52.661+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-28T08:13:52.663+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-28T08:13:52.664+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-28T08:13:52.665+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-28T08:13:52.667+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-28T08:13:52.670+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-28T08:13:52.671+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-28T08:13:52.676+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-28T08:13:52.678+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-28T08:13:52.679+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-28T08:13:52.680+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-28T08:13:52.681+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-28T08:13:52.683+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-28T08:13:52.684+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-28T08:13:52.686+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-28T08:13:52.688+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.690+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-28T08:13:52.692+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-28T08:13:52.694+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-28T08:13:52.695+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-28T08:13:52.696+0000] {subprocess.py:106} INFO - 
[2025-03-28T08:13:52.697+0000] {subprocess.py:106} INFO - Driver stacktrace:
[2025-03-28T08:13:52.699+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-03-28T08:13:52.701+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-03-28T08:13:52.702+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-03-28T08:13:52.704+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-28T08:13:52.705+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-28T08:13:52.706+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-28T08:13:52.708+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-03-28T08:13:52.710+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-03-28T08:13:52.712+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-03-28T08:13:52.713+0000] {subprocess.py:106} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-03-28T08:13:52.715+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-03-28T08:13:52.716+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-03-28T08:13:52.718+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-03-28T08:13:52.719+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-03-28T08:13:52.720+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-28T08:13:52.721+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-03-28T08:13:52.722+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-03-28T08:13:52.724+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-03-28T08:13:52.726+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-03-28T08:13:52.727+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2458)
[2025-03-28T08:13:52.729+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1039)
[2025-03-28T08:13:52.730+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-03-28T08:13:52.731+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-03-28T08:13:52.732+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
[2025-03-28T08:13:52.734+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1037)
[2025-03-28T08:13:52.736+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:3516)
[2025-03-28T08:13:52.738+0000] {subprocess.py:106} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-03-28T08:13:52.739+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:4310)
[2025-03-28T08:13:52.740+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-28T08:13:52.742+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-28T08:13:52.744+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-28T08:13:52.746+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-28T08:13:52.747+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-28T08:13:52.748+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:4308)
[2025-03-28T08:13:52.749+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:3516)
[2025-03-28T08:13:52.751+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:903)
[2025-03-28T08:13:52.752+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:70)
[2025-03-28T08:13:52.753+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[2025-03-28T08:13:52.754+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
[2025-03-28T08:13:52.756+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
[2025-03-28T08:13:52.761+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
[2025-03-28T08:13:52.764+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-03-28T08:13:52.766+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-28T08:13:52.767+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-28T08:13:52.768+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-28T08:13:52.770+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-28T08:13:52.770+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-28T08:13:52.771+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-03-28T08:13:52.773+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-03-28T08:13:52.774+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-03-28T08:13:52.777+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-03-28T08:13:52.778+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-03-28T08:13:52.779+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-28T08:13:52.780+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-03-28T08:13:52.781+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-03-28T08:13:52.782+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-28T08:13:52.783+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-28T08:13:52.784+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-03-28T08:13:52.785+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-03-28T08:13:52.786+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-03-28T08:13:52.787+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-03-28T08:13:52.788+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-03-28T08:13:52.788+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-03-28T08:13:52.789+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-03-28T08:13:52.791+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-03-28T08:13:52.793+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
[2025-03-28T08:13:52.795+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-28T08:13:52.796+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-28T08:13:52.797+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-28T08:13:52.798+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-28T08:13:52.799+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-28T08:13:52.800+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-28T08:13:52.801+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-28T08:13:52.802+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-28T08:13:52.802+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-28T08:13:52.803+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-28T08:13:52.804+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-28T08:13:52.805+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-28T08:13:52.806+0000] {subprocess.py:106} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.807+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-28T08:13:52.809+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-28T08:13:52.811+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-28T08:13:52.812+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-28T08:13:52.814+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-28T08:13:52.816+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-28T08:13:52.818+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-28T08:13:52.818+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-28T08:13:52.819+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-28T08:13:52.820+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-28T08:13:52.821+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-28T08:13:52.822+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-28T08:13:52.823+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-28T08:13:52.826+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-28T08:13:52.827+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-28T08:13:52.829+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-28T08:13:52.830+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-28T08:13:52.831+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-28T08:13:52.832+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-28T08:13:52.833+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-28T08:13:52.835+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-28T08:13:52.836+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-28T08:13:52.837+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-28T08:13:52.838+0000] {subprocess.py:106} INFO - 	... 1 more
[2025-03-28T08:13:52.839+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-28T08:13:52.840+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-28T08:13:52.842+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-28T08:13:52.844+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-28T08:13:52.845+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-28T08:13:52.936+0000] {subprocess.py:106} INFO - 
[2025-03-28T08:13:53.454+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-28T08:13:53.478+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-28T08:13:53.479+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_postgres_script, run_id=scheduled__2025-03-27T08:00:00+00:00, execution_date=20250327T080000, start_date=20250328T081342, end_date=20250328T081353
[2025-03-28T08:13:53.503+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-28T08:13:53.504+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-28T08:13:53.505+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-03-28 08:13:06.901413+00:00
[2025-03-28T08:13:53.506+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-28T08:13:53.521+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T08:13:53.536+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T08:13:53.538+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
