[2025-03-30T10:31:39.416+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T10:31:39.624+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-28T08:00:00+00:00 [queued]>
[2025-03-30T10:31:39.643+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-28T08:00:00+00:00 [queued]>
[2025-03-30T10:31:39.646+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T10:31:39.666+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_postgres_script> on 2025-03-28 08:00:00+00:00
[2025-03-30T10:31:39.674+0000] {standard_task_runner.py:72} INFO - Started process 744 to run task
[2025-03-30T10:31:39.681+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_postgres_script', 'scheduled__2025-03-28T08:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp4low386q']
[2025-03-30T10:31:39.684+0000] {standard_task_runner.py:105} INFO - Job 148: Subtask run_postgres_script
[2025-03-30T10:31:39.765+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-28T08:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-03-30T10:31:39.943+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_postgres_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-28T08:00:00+00:00'
[2025-03-30T10:31:39.947+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T10:31:39.949+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T10:31:39.950+0000] {logging_mixin.py:190} INFO - Current task name:run_postgres_script state:running start_date:2025-03-30 10:31:39.626362+00:00
[2025-03-30T10:31:39.951+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-30T10:31:39.953+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T10:31:39.955+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T10:31:39.956+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/postgres.py']
[2025-03-30T10:31:39.973+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T10:31:45.220+0000] {subprocess.py:106} INFO - 25/03/30 10:31:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-30T10:31:45.573+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-30T10:31:45.577+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-30T10:31:47.243+0000] {subprocess.py:106} INFO - 25/03/30 10:31:47 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-03-30T10:31:59.807+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                [Stage 1:>                                                          (0 + 1) / 1]                                                                                [Stage 2:>                                                          (0 + 1) / 1]25/03/30 10:31:59 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
[2025-03-30T10:31:59.808+0000] {subprocess.py:106} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:31:59.811+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:31:59.816+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:31:59.818+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:31:59.820+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:31:59.822+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:31:59.824+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:31:59.825+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:31:59.830+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:31:59.833+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:31:59.836+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:31:59.838+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:31:59.841+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:31:59.844+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:31:59.856+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:31:59.858+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:31:59.871+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:31:59.873+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:31:59.875+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:31:59.879+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:31:59.883+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:31:59.885+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:31:59.886+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:31:59.888+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:31:59.893+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:31:59.899+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:31:59.902+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:31:59.904+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:31:59.905+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:31:59.906+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:31:59.908+0000] {subprocess.py:106} INFO - 25/03/30 10:31:59 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:31:59.910+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:31:59.913+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:31:59.916+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:31:59.920+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:31:59.936+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:31:59.949+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:31:59.955+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:31:59.960+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:31:59.965+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:31:59.967+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:31:59.984+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:31:59.987+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:31:59.989+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:31:59.991+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:31:59.993+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:31:59.997+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:32:00.001+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:32:00.003+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:32:00.007+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:32:00.009+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:32:00.011+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:32:00.014+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:32:00.017+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:32:00.020+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:32:00.023+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.025+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:32:00.027+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:32:00.033+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:32:00.036+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:32:00.038+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:32:00.040+0000] {subprocess.py:106} INFO - 25/03/30 10:31:59 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
[2025-03-30T10:32:00.402+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-30T10:32:00.406+0000] {subprocess.py:106} INFO - |                city|      local_time|temperature|wind_kph|humidity|feelslike|precip_mm| text|                icon|
[2025-03-30T10:32:00.414+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-30T10:32:00.420+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 04:00|       10.2|     3.2|      77|     10.6|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.425+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 09:00|       14.5|     4.0|      56|     15.1|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.430+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 15:00|       19.0|     4.3|      38|     19.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.436+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 22:00|       12.9|    10.1|      83|     12.1|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.440+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 04:00|        6.8|     5.8|      70|      5.9|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.449+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 09:00|        7.9|     5.4|      66|      7.2|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.455+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 15:00|       15.4|     5.4|      39|     15.4|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.458+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 22:00|       11.5|     6.5|      52|     11.1|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.465+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 04:00|       11.6|     4.7|      68|     11.6|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.467+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 09:00|       14.5|     4.7|      59|     15.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.471+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 15:00|       16.5|    16.6|      60|     16.5|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.474+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 22:00|       13.4|     6.5|      80|     13.3|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.479+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 04:00|       11.9|     7.2|      79|     11.4|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.481+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 09:00|       14.0|     6.8|      66|     14.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.484+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 15:00|       18.5|    15.1|      50|     18.5|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.486+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 22:00|       14.2|    11.5|      76|     13.5|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.488+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-30T10:32:00.490+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:32:00.491+0000] {subprocess.py:106} INFO - Error: An error occurred while calling o43.save.
[2025-03-30T10:32:00.493+0000] {subprocess.py:106} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.496+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:32:00.499+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:32:00.501+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:32:00.503+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:32:00.505+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:32:00.509+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:32:00.512+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:32:00.514+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:32:00.516+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:32:00.517+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:32:00.519+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:32:00.521+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:32:00.522+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:32:00.524+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:32:00.526+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:32:00.528+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:32:00.530+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:32:00.532+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:32:00.534+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:32:00.537+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:32:00.539+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:32:00.541+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:32:00.542+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:32:00.544+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:32:00.546+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.547+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:32:00.549+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:32:00.550+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:32:00.552+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:32:00.553+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:32:00.555+0000] {subprocess.py:106} INFO - Driver stacktrace:
[2025-03-30T10:32:00.556+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-03-30T10:32:00.558+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-03-30T10:32:00.559+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-03-30T10:32:00.560+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-30T10:32:00.562+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-30T10:32:00.563+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-30T10:32:00.564+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-03-30T10:32:00.566+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-03-30T10:32:00.567+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-03-30T10:32:00.568+0000] {subprocess.py:106} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-03-30T10:32:00.569+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-03-30T10:32:00.570+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-03-30T10:32:00.571+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-03-30T10:32:00.572+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-03-30T10:32:00.573+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-30T10:32:00.574+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-03-30T10:32:00.575+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-03-30T10:32:00.577+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-03-30T10:32:00.578+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-03-30T10:32:00.580+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2458)
[2025-03-30T10:32:00.581+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1039)
[2025-03-30T10:32:00.582+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-03-30T10:32:00.583+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-03-30T10:32:00.584+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
[2025-03-30T10:32:00.585+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1037)
[2025-03-30T10:32:00.587+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:3516)
[2025-03-30T10:32:00.588+0000] {subprocess.py:106} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-03-30T10:32:00.589+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:4310)
[2025-03-30T10:32:00.590+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-30T10:32:00.592+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-30T10:32:00.593+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-30T10:32:00.594+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-30T10:32:00.596+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-30T10:32:00.598+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:4308)
[2025-03-30T10:32:00.599+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:3516)
[2025-03-30T10:32:00.600+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:903)
[2025-03-30T10:32:00.601+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:70)
[2025-03-30T10:32:00.603+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[2025-03-30T10:32:00.604+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
[2025-03-30T10:32:00.605+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
[2025-03-30T10:32:00.606+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
[2025-03-30T10:32:00.607+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-03-30T10:32:00.609+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-30T10:32:00.610+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-30T10:32:00.612+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-30T10:32:00.614+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-30T10:32:00.615+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-30T10:32:00.617+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-03-30T10:32:00.618+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-03-30T10:32:00.619+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-03-30T10:32:00.621+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-03-30T10:32:00.622+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-03-30T10:32:00.623+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-30T10:32:00.624+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-03-30T10:32:00.625+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-03-30T10:32:00.627+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-30T10:32:00.628+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-30T10:32:00.630+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-03-30T10:32:00.631+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-03-30T10:32:00.632+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-03-30T10:32:00.633+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-03-30T10:32:00.634+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-03-30T10:32:00.636+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-03-30T10:32:00.637+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-03-30T10:32:00.638+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-03-30T10:32:00.640+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
[2025-03-30T10:32:00.641+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-30T10:32:00.642+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-30T10:32:00.644+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-30T10:32:00.646+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-30T10:32:00.647+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-30T10:32:00.649+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-30T10:32:00.650+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-30T10:32:00.651+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-30T10:32:00.653+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-30T10:32:00.654+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-30T10:32:00.655+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-30T10:32:00.656+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:32:00.657+0000] {subprocess.py:106} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.658+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:32:00.660+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:32:00.661+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:32:00.663+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:32:00.664+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:32:00.666+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:32:00.667+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:32:00.668+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:32:00.669+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:32:00.670+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:32:00.672+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:32:00.673+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:32:00.674+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:32:00.675+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:32:00.677+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:32:00.678+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:32:00.680+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:32:00.681+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:32:00.682+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:32:00.683+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:32:00.684+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:32:00.686+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:32:00.687+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:32:00.688+0000] {subprocess.py:106} INFO - 	... 1 more
[2025-03-30T10:32:00.689+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.691+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:32:00.692+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:32:00.693+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:32:00.695+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:32:01.015+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:32:01.746+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-30T10:32:01.788+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T10:32:01.790+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_postgres_script, run_id=scheduled__2025-03-28T08:00:00+00:00, execution_date=20250328T080000, start_date=20250330T103139, end_date=20250330T103201
[2025-03-30T10:32:01.837+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-30T10:32:01.840+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-30T10:32:01.843+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-03-30 10:25:51.880233+00:00
[2025-03-30T10:32:01.845+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-30T10:32:01.899+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T10:32:01.923+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T10:32:01.926+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
