[2025-03-25T07:29:32.099+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T07:29:32.241+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_bbdd_script manual__2025-03-25T07:27:42.433355+00:00 [queued]>
[2025-03-25T07:29:32.251+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_bbdd_script manual__2025-03-25T07:27:42.433355+00:00 [queued]>
[2025-03-25T07:29:32.252+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-25T07:29:32.264+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_bbdd_script> on 2025-03-25 07:27:42.433355+00:00
[2025-03-25T07:29:32.269+0000] {standard_task_runner.py:72} INFO - Started process 14946 to run task
[2025-03-25T07:29:32.272+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_bbdd_script', 'manual__2025-03-25T07:27:42.433355+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpd_2dt1e3']
[2025-03-25T07:29:32.274+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask run_bbdd_script
[2025-03-25T07:29:32.309+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_bbdd_script manual__2025-03-25T07:27:42.433355+00:00 [running]> on host 16f770ed73e8
[2025-03-25T07:29:32.379+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_bbdd_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T07:27:42.433355+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T07:27:42.433355+00:00'
[2025-03-25T07:29:32.381+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-25T07:29:32.383+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-25T07:29:32.384+0000] {logging_mixin.py:190} INFO - Current task name:run_bbdd_script state:running start_date:2025-03-25 07:29:32.242175+00:00
[2025-03-25T07:29:32.385+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-25T07:29:32.386+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T07:29:32.387+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-25T07:29:32.389+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark spark-submit --jars /opt/spark/jars/postgresql-42.2.27.jar /opt/***/dags/main_bbdd.py']
[2025-03-25T07:29:32.398+0000] {subprocess.py:99} INFO - Output:
[2025-03-25T07:29:32.515+0000] {subprocess.py:106} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-03-25T07:29:32.516+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-25T07:29:32.524+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-25T07:29:32.533+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-25T07:29:32.535+0000] {logging_mixin.py:190} INFO - Task start:2025-03-25 07:29:32.242175+00:00 end:2025-03-25 07:29:32.533389+00:00 duration:0.291214
[2025-03-25T07:29:32.536+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): run_bbdd_script> dag:<DAG: daily_weather_etl> dagrun:<DagRun daily_weather_etl @ 2025-03-25 07:27:42.433355+00:00: manual__2025-03-25T07:27:42.433355+00:00, state:running, queued_at: 2025-03-25 07:27:42.451599+00:00. externally triggered: True>
[2025-03-25T07:29:32.537+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-03-25T07:29:32.537+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_weather_etl, task_id=run_bbdd_script, run_id=manual__2025-03-25T07:27:42.433355+00:00, execution_date=20250325T072742, start_date=20250325T072932, end_date=20250325T072932
[2025-03-25T07:29:32.563+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T07:29:32.565+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task run_bbdd_script (Bash command failed. The command returned a non-zero exit code 1.; 14946)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-25T07:29:32.606+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T07:29:32.627+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T07:29:32.630+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
