[2025-03-30T10:31:39.227+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T10:31:39.434+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-30T10:31:39.453+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-30T10:31:39.456+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-30T10:31:39.481+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_postgres_script> on 2025-03-29 08:00:00+00:00
[2025-03-30T10:31:39.490+0000] {standard_task_runner.py:72} INFO - Started process 742 to run task
[2025-03-30T10:31:39.499+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_postgres_script', 'scheduled__2025-03-29T08:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmps53cm_b3']
[2025-03-30T10:31:39.502+0000] {standard_task_runner.py:105} INFO - Job 147: Subtask run_postgres_script
[2025-03-30T10:31:39.583+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-29T08:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-03-30T10:31:39.727+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_postgres_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T08:00:00+00:00'
[2025-03-30T10:31:39.731+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T10:31:39.733+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T10:31:39.735+0000] {logging_mixin.py:190} INFO - Current task name:run_postgres_script state:running start_date:2025-03-30 10:31:39.436299+00:00
[2025-03-30T10:31:39.736+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-30T10:31:39.738+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T10:31:39.740+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-30T10:31:39.742+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/postgres.py']
[2025-03-30T10:31:39.767+0000] {subprocess.py:99} INFO - Output:
[2025-03-30T10:31:45.017+0000] {subprocess.py:106} INFO - 25/03/30 10:31:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-30T10:31:45.403+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-30T10:31:45.405+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-30T10:31:59.697+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                [Stage 1:>                                                          (0 + 1) / 1]                                                                                25/03/30 10:31:59 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
[2025-03-30T10:31:59.699+0000] {subprocess.py:106} INFO - java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:31:59.700+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:31:59.703+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:31:59.705+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:31:59.708+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:31:59.710+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:31:59.712+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:31:59.716+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:31:59.725+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:31:59.728+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:31:59.732+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:31:59.733+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:31:59.736+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:31:59.738+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:31:59.740+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:31:59.741+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:31:59.743+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:31:59.747+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:31:59.751+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:31:59.761+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:31:59.764+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:31:59.766+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:31:59.768+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:31:59.769+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:31:59.773+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:31:59.774+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:31:59.776+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:31:59.784+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:31:59.788+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:31:59.790+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:31:59.792+0000] {subprocess.py:106} INFO - 25/03/30 10:31:59 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:31:59.794+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:31:59.797+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:31:59.805+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:31:59.806+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:31:59.809+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:31:59.811+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:31:59.816+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:31:59.818+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:31:59.820+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:31:59.822+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:31:59.826+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:31:59.832+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:31:59.836+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:31:59.838+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:31:59.840+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:31:59.843+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:31:59.851+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:31:59.864+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:31:59.868+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:31:59.870+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:31:59.878+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:31:59.881+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:31:59.883+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:31:59.885+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:31:59.887+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:31:59.888+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:31:59.893+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:31:59.897+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:31:59.899+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:31:59.903+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:31:59.905+0000] {subprocess.py:106} INFO - 25/03/30 10:31:59 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
[2025-03-30T10:32:00.382+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-30T10:32:00.385+0000] {subprocess.py:106} INFO - |                city|      local_time|temperature|wind_kph|humidity|feelslike|precip_mm| text|                icon|
[2025-03-30T10:32:00.389+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-30T10:32:00.393+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 04:00|       10.2|     3.2|      77|     10.6|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.401+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 09:00|       14.5|     4.0|      56|     15.1|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.407+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 15:00|       19.0|     4.3|      38|     19.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.412+0000] {subprocess.py:106} INFO - |               elche|2025-03-26 22:00|       12.9|    10.1|      83|     12.1|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.420+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 04:00|        6.8|     5.8|      70|      5.9|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.425+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 09:00|        7.9|     5.4|      66|      7.2|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.433+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 15:00|       15.4|     5.4|      39|     15.4|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.439+0000] {subprocess.py:106} INFO - |              madrid|2025-03-26 22:00|       11.5|     6.5|      52|     11.1|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.445+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 04:00|       11.6|     4.7|      68|     11.6|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.454+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 09:00|       14.5|     4.7|      59|     15.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.459+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 15:00|       16.5|    16.6|      60|     16.5|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.464+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-26 22:00|       13.4|     6.5|      80|     13.3|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.466+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 04:00|       11.9|     7.2|      79|     11.4|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.468+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 09:00|       14.0|     6.8|      66|     14.0|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.471+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 15:00|       18.5|    15.1|      50|     18.5|      0.0|Sunny|//cdn.weatherapi....|
[2025-03-30T10:32:00.472+0000] {subprocess.py:106} INFO - |          torrevieja|2025-03-26 22:00|       14.2|    11.5|      76|     13.5|      0.0|Clear|//cdn.weatherapi....|
[2025-03-30T10:32:00.476+0000] {subprocess.py:106} INFO - +--------------------+----------------+-----------+--------+--------+---------+---------+-----+--------------------+
[2025-03-30T10:32:00.478+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:32:00.481+0000] {subprocess.py:106} INFO - Error: An error occurred while calling o43.save.
[2025-03-30T10:32:00.484+0000] {subprocess.py:106} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2) (3c3c1f66214b executor driver): java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.486+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:32:00.488+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:32:00.490+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:32:00.491+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:32:00.494+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:32:00.497+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:32:00.499+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:32:00.500+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:32:00.502+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:32:00.503+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:32:00.505+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:32:00.506+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:32:00.508+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:32:00.509+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:32:00.511+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:32:00.513+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:32:00.515+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:32:00.517+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:32:00.518+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:32:00.522+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:32:00.523+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:32:00.525+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:32:00.526+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:32:00.528+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:32:00.530+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.531+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:32:00.533+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:32:00.535+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:32:00.538+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:32:00.540+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:32:00.541+0000] {subprocess.py:106} INFO - Driver stacktrace:
[2025-03-30T10:32:00.543+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-03-30T10:32:00.545+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-03-30T10:32:00.547+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-03-30T10:32:00.549+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-30T10:32:00.550+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-30T10:32:00.552+0000] {subprocess.py:106} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-30T10:32:00.554+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-03-30T10:32:00.555+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-03-30T10:32:00.556+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-03-30T10:32:00.558+0000] {subprocess.py:106} INFO - 	at scala.Option.foreach(Option.scala:407)
[2025-03-30T10:32:00.559+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-03-30T10:32:00.560+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-03-30T10:32:00.562+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-03-30T10:32:00.563+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-03-30T10:32:00.564+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-30T10:32:00.566+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-03-30T10:32:00.566+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-03-30T10:32:00.568+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-03-30T10:32:00.569+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-03-30T10:32:00.570+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2458)
[2025-03-30T10:32:00.571+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1039)
[2025-03-30T10:32:00.572+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-03-30T10:32:00.573+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-03-30T10:32:00.574+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.withScope(RDD.scala:410)
[2025-03-30T10:32:00.576+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1037)
[2025-03-30T10:32:00.577+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:3516)
[2025-03-30T10:32:00.579+0000] {subprocess.py:106} INFO - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[2025-03-30T10:32:00.580+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:4310)
[2025-03-30T10:32:00.581+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-30T10:32:00.582+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-30T10:32:00.583+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-30T10:32:00.584+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-30T10:32:00.585+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-30T10:32:00.587+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:4308)
[2025-03-30T10:32:00.588+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:3516)
[2025-03-30T10:32:00.589+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.saveTable(JdbcUtils.scala:903)
[2025-03-30T10:32:00.590+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:70)
[2025-03-30T10:32:00.592+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
[2025-03-30T10:32:00.593+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
[2025-03-30T10:32:00.595+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
[2025-03-30T10:32:00.596+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
[2025-03-30T10:32:00.598+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
[2025-03-30T10:32:00.599+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-30T10:32:00.600+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-30T10:32:00.601+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-30T10:32:00.603+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-30T10:32:00.604+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-30T10:32:00.605+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
[2025-03-30T10:32:00.606+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
[2025-03-30T10:32:00.608+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
[2025-03-30T10:32:00.609+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
[2025-03-30T10:32:00.610+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
[2025-03-30T10:32:00.612+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-30T10:32:00.614+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
[2025-03-30T10:32:00.615+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
[2025-03-30T10:32:00.616+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-30T10:32:00.618+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
[2025-03-30T10:32:00.619+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
[2025-03-30T10:32:00.620+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
[2025-03-30T10:32:00.622+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
[2025-03-30T10:32:00.623+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
[2025-03-30T10:32:00.624+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
[2025-03-30T10:32:00.625+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:869)
[2025-03-30T10:32:00.626+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-03-30T10:32:00.628+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-03-30T10:32:00.630+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
[2025-03-30T10:32:00.631+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-30T10:32:00.632+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-30T10:32:00.633+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-30T10:32:00.635+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-30T10:32:00.636+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-30T10:32:00.637+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-30T10:32:00.638+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-30T10:32:00.640+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-30T10:32:00.641+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-30T10:32:00.643+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-30T10:32:00.644+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-30T10:32:00.646+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-30T10:32:00.647+0000] {subprocess.py:106} INFO - Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO pro_raw_api.daily_weather ("city","local_time","temperature","wind_kph","humidity","feelslike","precip_mm","text","icon") VALUES ('elche','2025-03-26 04:00',10.2,3.2,77,10.6,0.0,'Clear','//cdn.weatherapi.com/weather/64x64/night/113.png') was aborted: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.649+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.  Call getNextException to see other errors in the batch.
[2025-03-30T10:32:00.650+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:171)
[2025-03-30T10:32:00.651+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2298)
[2025-03-30T10:32:00.653+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:520)
[2025-03-30T10:32:00.654+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
[2025-03-30T10:32:00.655+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:901)
[2025-03-30T10:32:00.656+0000] {subprocess.py:106} INFO - 	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
[2025-03-30T10:32:00.657+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:753)
[2025-03-30T10:32:00.658+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:904)
[2025-03-30T10:32:00.660+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:903)
[2025-03-30T10:32:00.661+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1039)
[2025-03-30T10:32:00.663+0000] {subprocess.py:106} INFO - 	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1039)
[2025-03-30T10:32:00.664+0000] {subprocess.py:106} INFO - 	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2433)
[2025-03-30T10:32:00.665+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-30T10:32:00.666+0000] {subprocess.py:106} INFO - 	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-30T10:32:00.667+0000] {subprocess.py:106} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-30T10:32:00.669+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-30T10:32:00.670+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-30T10:32:00.671+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-30T10:32:00.672+0000] {subprocess.py:106} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-30T10:32:00.674+0000] {subprocess.py:106} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-30T10:32:00.675+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-03-30T10:32:00.676+0000] {subprocess.py:106} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-03-30T10:32:00.678+0000] {subprocess.py:106} INFO - 	... 1 more
[2025-03-30T10:32:00.679+0000] {subprocess.py:106} INFO - Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_city_local_time"
[2025-03-30T10:32:00.681+0000] {subprocess.py:106} INFO -   Detail: Key (city, local_time)=(elche, 2025-03-26 04:00) already exists.
[2025-03-30T10:32:00.682+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
[2025-03-30T10:32:00.683+0000] {subprocess.py:106} INFO - 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
[2025-03-30T10:32:00.685+0000] {subprocess.py:106} INFO - 	... 21 more
[2025-03-30T10:32:00.842+0000] {subprocess.py:106} INFO - 
[2025-03-30T10:32:01.611+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-30T10:32:01.648+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T10:32:01.651+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_postgres_script, run_id=scheduled__2025-03-29T08:00:00+00:00, execution_date=20250329T080000, start_date=20250330T103139, end_date=20250330T103201
[2025-03-30T10:32:01.688+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-30T10:32:01.690+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-30T10:32:01.692+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-03-30 10:25:52.225372+00:00
[2025-03-30T10:32:01.694+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-30T10:32:01.749+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T10:32:01.781+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T10:32:01.784+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-31T07:15:17.105+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T07:15:17.152+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-31T07:15:17.169+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-29T08:00:00+00:00 [queued]>
[2025-03-31T07:15:17.171+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-31T07:15:17.197+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_postgres_script> on 2025-03-29 08:00:00+00:00
[2025-03-31T07:15:17.211+0000] {standard_task_runner.py:72} INFO - Started process 10925 to run task
[2025-03-31T07:15:17.219+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_etl', 'run_postgres_script', 'scheduled__2025-03-29T08:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpy92_njfr']
[2025-03-31T07:15:17.223+0000] {standard_task_runner.py:105} INFO - Job 198: Subtask run_postgres_script
[2025-03-31T07:15:17.325+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_weather_etl.run_postgres_script scheduled__2025-03-29T08:00:00+00:00 [running]> on host 3c3c1f66214b
[2025-03-31T07:15:17.876+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_etl' AIRFLOW_CTX_TASK_ID='run_postgres_script' AIRFLOW_CTX_EXECUTION_DATE='2025-03-29T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-29T08:00:00+00:00'
[2025-03-31T07:15:17.879+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T07:15:17.881+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T07:15:17.883+0000] {logging_mixin.py:190} INFO - Current task name:run_postgres_script state:running start_date:2025-03-31 07:15:17.153806+00:00
[2025-03-31T07:15:17.884+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl and current dag run status:running
[2025-03-31T07:15:17.885+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T07:15:17.887+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T07:15:17.889+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/postgres.py']
[2025-03-31T07:15:17.906+0000] {subprocess.py:99} INFO - Output:
[2025-03-31T07:15:22.143+0000] {subprocess.py:106} INFO - 25/03/31 07:15:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-31T07:15:22.417+0000] {subprocess.py:106} INFO - Setting default log level to "WARN".
[2025-03-31T07:15:22.419+0000] {subprocess.py:106} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-03-31T07:15:33.143+0000] {subprocess.py:106} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                [Stage 1:>                                                          (0 + 1) / 1]                                                                                +--------------------+----------+-----+-----------+--------+--------+---------+---------+----------------+--------------------+
[2025-03-31T07:15:33.145+0000] {subprocess.py:106} INFO - |                city|      date| time|temperature|wind_kph|humidity|feelslike|precip_mm|            text|                icon|
[2025-03-31T07:15:33.146+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+----------------+--------------------+
[2025-03-31T07:15:33.147+0000] {subprocess.py:106} INFO - |               elche|2025-03-28|04:00|       10.7|     9.1|      83|     10.7|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.149+0000] {subprocess.py:106} INFO - |               elche|2025-03-28|09:00|       12.0|    14.2|      61|     12.0|      0.0|   Partly Cloudy|//cdn.weatherapi....|
[2025-03-31T07:15:33.150+0000] {subprocess.py:106} INFO - |               elche|2025-03-28|15:00|       23.0|    14.8|      25|     23.0|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.151+0000] {subprocess.py:106} INFO - |               elche|2025-03-28|22:00|       11.9|     5.5|      91|     11.9|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.152+0000] {subprocess.py:106} INFO - |               elche|2025-03-29|04:00|       14.1|    14.7|      45|     14.1|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.154+0000] {subprocess.py:106} INFO - |               elche|2025-03-29|09:00|       13.4|    20.8|      40|     13.4|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.156+0000] {subprocess.py:106} INFO - |               elche|2025-03-29|15:00|       24.1|    17.2|      16|     24.1|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.157+0000] {subprocess.py:106} INFO - |               elche|2025-03-29|22:00|       13.3|     3.6|      59|     13.3|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.158+0000] {subprocess.py:106} INFO - |              madrid|2025-03-28|04:00|        7.6|     4.6|      80|      7.6|      0.0|    Mostly Clear|//cdn.weatherapi....|
[2025-03-31T07:15:33.160+0000] {subprocess.py:106} INFO - |              madrid|2025-03-28|09:00|        4.6|     7.3|      89|      4.6|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.161+0000] {subprocess.py:106} INFO - |              madrid|2025-03-28|15:00|       15.6|     1.6|      48|     15.6|      0.0|    Mostly Clear|//cdn.weatherapi....|
[2025-03-31T07:15:33.162+0000] {subprocess.py:106} INFO - |              madrid|2025-03-28|22:00|       11.0|     2.7|      68|     11.0|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.163+0000] {subprocess.py:106} INFO - |              madrid|2025-03-29|04:00|        7.7|     5.7|      75|      7.7|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.165+0000] {subprocess.py:106} INFO - |              madrid|2025-03-29|09:00|        5.5|     5.1|      79|      5.5|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.167+0000] {subprocess.py:106} INFO - |              madrid|2025-03-29|15:00|       15.8|     4.6|      47|     15.8|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.168+0000] {subprocess.py:106} INFO - |              madrid|2025-03-29|22:00|       10.0|    16.2|      53|     10.0|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.169+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-28|04:00|        9.5|     8.2|      74|      9.5|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.171+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-28|09:00|        9.9|     5.6|      76|      9.9|      0.0|          Cloudy|//cdn.weatherapi....|
[2025-03-31T07:15:33.173+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-28|15:00|       18.4|    12.3|      67|     18.4|      0.5|Moderate Drizzle|//cdn.weatherapi....|
[2025-03-31T07:15:33.174+0000] {subprocess.py:106} INFO - |san juan de alicante|2025-03-28|22:00|       12.0|     3.7|      85|     12.0|      0.0|           Sunny|//cdn.weatherapi....|
[2025-03-31T07:15:33.176+0000] {subprocess.py:106} INFO - +--------------------+----------+-----+-----------+--------+--------+---------+---------+----------------+--------------------+
[2025-03-31T07:15:33.177+0000] {subprocess.py:106} INFO - only showing top 20 rows
[2025-03-31T07:15:33.178+0000] {subprocess.py:106} INFO - 
[2025-03-31T07:15:33.179+0000] {subprocess.py:106} INFO - Datos registrados correctamente en la bbdd
[2025-03-31T07:15:33.707+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T07:15:33.746+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T07:15:33.747+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=daily_weather_etl, task_id=run_postgres_script, run_id=scheduled__2025-03-29T08:00:00+00:00, execution_date=20250329T080000, start_date=20250331T071517, end_date=20250331T071533
[2025-03-31T07:15:33.788+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-31T07:15:33.790+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-31T07:15:33.791+0000] {logging_mixin.py:190} INFO - Dag name:daily_weather_etl queued_at:2025-03-31 07:13:46.991613+00:00
[2025-03-31T07:15:33.793+0000] {logging_mixin.py:190} INFO - Task hostname:3c3c1f66214b operator:BashOperator
[2025-03-31T07:15:33.835+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T07:15:33.860+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T07:15:33.863+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
